services:
  backend:

    restart: always
    env_file:
      - .env
    environment:
      # переменные окружения
      APP_UVICORN: ${APP_UVICORN}
      APP_PG: ${APP_PG}
    depends_on:
      - postgres
    image: ${IMAGE_BACKEND}
    ports:
      # вывести ли порты в материнскую систему
      - ${PORTS_BACKEND_LINK}

  postgres:
    image: postgres:17.0
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    ports:
      - ${PORTS_POSTGRES_LINK}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/pg/:/var/lib/postgresql/data/